FROM  nginx-lua:1.10.3-alpine-2
LABEL maintainer.name="Rafael Solano Martinez"
LABEL maintainer.mail="rafael.solano@resultier.com"
LABEL description="Base Web Data Store Server"

RUN apk add --no-cache vim 
RUN apk add --no-cache ca-certificates openssl 
RUN apk add --no-cache bash 
RUN apk add --no-cache curl jq 
RUN update-ca-certificates

RUN wget -O /tmp/consul-template.tgz https://s3.amazonaws.com/nomad-static.shout.tv/consul-template_0.19.3-with_patch_1f7c022-linux_amd64.tgz
RUN tar -xzf /tmp/consul-template.tgz
RUN rm  -f   /tmp/consul-template.tgz
RUN mv consul-template /usr/bin/

ADD  resources/consul-cli.sh /usr/local/bin/
COPY wds.sh /usr/local/sbin/
ADD  resources/dclone.sh /usr/local/sbin/
ADD  resources/save-certs.sh /usr/local/sbin/
ADD  resources/pre-launch.sh /usr/local/sbin/
ADD  resources/consul-template.sh /usr/local/sbin/
RUN  chmod 755 /usr/local/sbin
RUN  chmod 755 /usr/local/sbin/*.sh
RUN  chmod 755 /usr/local/bin/*.sh

COPY etc /dclone/etc
RUN mkdir -p /dclone/etc/nginx/sites-enabled
RUN mkdir -p /dclone/etc/ssl/private
RUN chmod 700 /dclone/etc/ssl/private

RUN rm -f /etc/nginx/sites-enabled/*

RUN echo "alias ll='ls -l --color=auto'" >>/root/.bashrc

VOLUME /mnt/host

ENTRYPOINT ["/bin/bash", "/usr/local/sbin/wds.sh"]
