FROM wds:1.6
LABEL maintainer.name="Rafael Solano Martinez"
LABEL maintainer.mail="rafael.solano@resultier.com"
LABEL description="Snowy Owl Web Media Store Origin Server"

RUN  cd /dclone/etc/nginx/sites-available \
  && rm shout_wds_cache shout_wds_origin \
  && cd /dclone/etc/nginx/sites-enabled \
  && ln -s ../sites-available/shout_wms_origin
