FROM ubuntu:18.04
LABEL maintainer.name="Rafael Solano Martinez"
LABEL maintainer.mail="rafael.solano@resultier.com"
LABEL description="Base SRD Server"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y apt-utils
RUN apt-get install -y bash
RUN apt-get install -y vim
RUN apt-get install -y wget
RUN apt-get install -y grep
RUN apt-get install ca-certificates openssl
RUN update-ca-certificates

RUN wget -O /tmp/consul-template.tgz https://s3.amazonaws.com/nomad-static.shout.tv/consul-template_0.19.3-with_patch_1f7c022-linux_amd64.tgz \
    && tar -xzf /tmp/consul-template.tgz \
    && rm  -f   /tmp/consul-template.tgz \
    && mv consul-template /usr/bin/

COPY consul-template.sh /usr/local/sbin/
RUN  chmod +x /usr/local/sbin/consul-template.sh

COPY target/srd-server /usr/local/bin/
RUN  chmod +x /usr/local/bin/srd-server
RUN  mkdir -p /etc/srd-server

RUN echo "alias ll='ls -l --color=auto'" >>/root/.bashrc

VOLUME /mnt/host

ENTRYPOINT ["/bin/bash", "/usr/local/sbin/consul-template.sh", \
            "-log-level=debug", \
            "-exec-reload-signal=SIGHUP", \
            "-exec", "srd-server -p 8080 -n 0.0.0.0 --reuse-port"]
