INSERT INTO `gameplay`.`event` VALUES (null, NOW(), 'Jazz Game 8 Dec 2010', 'NEW', '87190', '2010-12-08', '2010-12-08', null, null, 0, null, null, 0, null);
INSERT INTO `gameplay`.`default_scoring` VALUES(1, 0, 0, 0, 10000, 10000, 10000, 0, 0, 15, 0, 50, 20, 10, 5, 5, 10, 5, 25);

INSERT INTO `gameplay`.`subscriber_ext` (`subscriber_id`, `opted_out`, `private_sub`) VALUES ('2', '0', '0');
INSERT INTO `gameplay`.`subscriber_ext` (`subscriber_id`, `opted_out`, `private_sub`) VALUES ('3', '0', '0');
INSERT INTO `gameplay`.`subscriber_ext` (`subscriber_id`, `opted_out`, `private_sub`) VALUES ('4', '0', '0');
INSERT INTO `gameplay`.`subscriber_ext` (`subscriber_id`, `opted_out`, `private_sub`) VALUES ('5', '0', '0');
INSERT INTO `gameplay`.`subscriber_ext` (`subscriber_id`, `opted_out`, `private_sub`) VALUES ('6', '0', '0');

INSERT INTO `gameplay`.`event_subscriber` (`event_id`, `subscriber_id`) VALUES ('1', '2');
INSERT INTO `gameplay`.`event_subscriber` (`event_id`, `subscriber_id`) VALUES ('1', '3');
INSERT INTO `gameplay`.`event_subscriber` (`event_id`, `subscriber_id`) VALUES ('1', '4');
INSERT INTO `gameplay`.`event_subscriber` (`event_id`, `subscriber_id`) VALUES ('1', '5');
INSERT INTO `gameplay`.`event_subscriber` (`event_id`, `subscriber_id`) VALUES ('1', '6');

#=========== metadata ===========
INSERT INTO `gameplay`.`metadata_relationship_type` (`name`) VALUES ('parent-child');
INSERT INTO `gameplay`.`metadata_relationship_type` (`name`) VALUES ('attribute');

INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('Sports League');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('Sports Conference');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('Sports Team');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('dummy1');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('dummy2');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('Entertainment');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('dummy3');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('Entertainment Item');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('dummy4');
INSERT INTO `gameplay`.`metadata_type` (`name`) VALUES ('team-logo-77x56');

#league
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NBA', 1, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NFL', 1, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('MLB', 1, 3);
#conference
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Eastern Conference', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Western Conference', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('American Football Conference', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('National Football Conference', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('National League', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('American League', 2, 1);
#division
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Atlantic', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Central', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Southeast', 2, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Southwest', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Northwest', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Pacific', 2, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('AFC East', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('AFC North', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('AFC South', 2, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('AFC West', 2, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NFC East', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NFC North', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NFC South', 2, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NFC West', 2, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NL East', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NL Central', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('NL West', 2, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('AL East', 2, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('ALCentral', 2, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('AL West', 2, 3);
#team
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Boston Celtics', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New Jersey Nets', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New York Knicks', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Philadelphia 76ers', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Toronto Raptors', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Chicago Bulls', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Cleveland Cavaliers', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Detroit Pistons', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Indiana Pacers', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Milwaukee Bucks', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Atlanta Hawks', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Charlotte Bobcats', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Miami Heat', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Orlando Magic', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Washington Wizards', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Dallas Mavericks', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Houston Rockets', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Memphis Grizzlies', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New Orleans Hornets', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('San Antonio Spurs', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Denver Nuggets', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Minnesota Timberwolves', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Portland Trail Blazers', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Oklahoma City Thunder', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Utah Jazz', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Golden State Warriors', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Los Angeles Lakers', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Los Angeles Clippers', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Phoenix Suns', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Sacramento Kings', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New England Patriots', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New York Jets', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Miami Dolphins', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Buffalo Bills', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Pittsburgh Steelers', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Baltimore Ravens', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Cleveland Browns', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Cincinnati Bengals', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Indianapolis Colts', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Jacksonville Jaguars', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Houston Texans', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Tennessee Titans', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Kansas City Chiefs', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('San Diego Chargers', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Oakland Raiders', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Denver Broncos', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Philadelphia Eagles', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New York Giants', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Dallas Cowboys', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Washington Redskins', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Chicago Bears', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Green Bay Packers', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Detroit Lions', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Minnesota Vikings', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Atlanta Falcons', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New Orleans Saints', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Tampa Bay Buccaneers', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Carolina Panthers', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Seattle Seahawks', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('St. Louis Rams', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('San Francisco 49ers', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Arizona Cardinals', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Atlanta Braves', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Florida Marlins', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New York Mets', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Washington Nationals', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Philadelphia Phillies', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Houston Astros', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Milwaukee Brewers', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('St. Louis Cardinals', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Chicago Cubs', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Pittsburgh Pirates', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Cincinnati Reds', 3, 6);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Arizona Diamondbacks', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Los Angeles Dodgers', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('San Francisco Giants', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('San Diego Padres', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Colorado Rockies', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Toronto Blue Jays', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Baltimore Orioles', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Tampa Bay Rays', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Boston Red Sox', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('New York Yankees', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Cleveland Indians', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Kansas City Royals', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Detroit Tigers', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Minnesota Twins', 3, 4);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Chicago White Sox', 3, 5);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Los Angeles Angels', 3, 1);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Oakland Athletics', 3, 2);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Seattle Mariners', 3, 3);
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Texas Rangers', 3, 4);
#entertainment leagues
INSERT INTO `gameplay`.`metadata` (metadata_id, `name`, `metadata_type_id`, `order`) VALUES (125, 'Awards Show', 6, 1);
#entertainment teams
INSERT INTO `gameplay`.`metadata` (`name`, `metadata_type_id`, `order`) VALUES ('Oscars', 8, 1);

INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 1, 4);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 1, 5);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 2, 6);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 2, 7);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 3, 8);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 3, 9);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 4, 10);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 4, 11);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 4, 12);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 5, 13);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 5, 14);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 5, 15);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 6, 16);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 6, 17);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 6, 18);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 6, 19);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 7, 20);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 7, 21);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 7, 22);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 7, 23);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 8, 24);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 8, 25);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 8, 26);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 9, 27);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 9, 28);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 9, 29);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 10, 30);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 10, 31);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 10, 32);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 10, 33);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 10, 34);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 11, 35);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 11, 36);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 11, 37);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 11, 38);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 11, 39);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 12, 40);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 12, 41);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 12, 42);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 12, 43);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 12, 44);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 13, 45);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 13, 46);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 13, 47);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 13, 48);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 13, 49);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 14, 50);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 14, 51);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 14, 52);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 14, 53);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 14, 54);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 15, 55);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 15, 56);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 15, 57);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 15, 58);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 15, 59);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 16, 60);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 16, 61);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 16, 62);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 16, 63);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 17, 64);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 17, 65);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 17, 66);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 17, 67);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 18, 68);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 18, 69);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 18, 70);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 18, 71);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 19, 72);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 19, 73);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 19, 74);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 19, 75);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 20, 76);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 20, 77);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 20, 78);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 20, 79);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 21, 80);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 21, 81);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 21, 82);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 21, 83);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 22, 84);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 22, 85);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 22, 86);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 22, 87);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 23, 88);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 23, 89);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 23, 90);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 23, 91);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 24, 92);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 24, 93);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 24, 94);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 24, 95);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 24, 96);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 25, 97);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 25, 98);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 25, 99);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 25, 100);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 25, 101);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 25, 102);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 26, 103);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 26, 104);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 26, 105);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 26, 106);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 26, 107);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 27, 108);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 27, 109);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 27, 110);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 27, 111);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 27, 112);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 28, 113);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 28, 114);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 28, 115);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 28, 116);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 28, 117);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 29, 118);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 29, 119);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 29, 120);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 29, 121);
INSERT INTO `gameplay`.`metadata_relationship` (`metadata_relationship_type_id`, `metadata_id_1`, `metadata_id_2`) VALUES (1, 125, 126); #entertainment/awards show -> oscars
